

services:
  db:
    image: ankane/pgvector:latest
    container_name: korely_db
    environment:
      POSTGRES_USER: korely_user
      POSTGRES_PASSWORD: korely_password
      POSTGRES_DB: korely_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: